In [12]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.preprocessing import LabelEncoder
from sklearn.svm import SVC

In [13]:
np.random.seed(123)
data = pd.read_csv('kipas0504.csv')
#data = data.iloc[:,1:-1]  #remove kolom id
label_encoder = LabelEncoder()
data.iloc[:,0] = label_encoder.fit_transform(data.iloc[:,0]).astype('float64') #mengubah value diagnosis menjadi 1 dan 0

In [14]:
paramater = data.iloc[:,1:-1]
target = data.iloc[:,0]

In [15]:
x_train, x_test, y_train, y_test = train_test_split(paramater.values, target.values, test_size = 0.2)

In [16]:
svc = SVC() # The default kernel adalah gaussian kernel
svc.fit(x_train, y_train)                        
prediction = svc.predict(x_test)     
print("Akurasi:",metrics.accuracy_score(y_test, prediction))

Akurasi: 0.09180327868852459


In [17]:
print(prediction)

[39. 25. 33. 33. 33. 39. 33. 33. 33. 33. 39. 39. 39. 39. 39. 25. 33. 33.
 39. 33. 33. 39. 39. 39. 33. 33. 33. 39. 33. 39. 33. 33. 33. 39. 39. 39.
 39. 33. 39. 25. 33. 39. 33. 33. 39. 33. 39. 39. 39. 33. 33. 39. 39. 33.
 33. 30. 33. 39. 33. 39. 33. 39. 39. 39. 33. 39. 33. 39. 39. 33. 39. 33.
 33. 39. 25. 39. 39. 33. 33. 33. 39. 33. 39. 39. 33. 33. 33. 39. 39. 33.
 25. 39. 33. 39. 39. 39. 39. 33. 39. 33. 33. 33. 39. 39. 33. 39. 39. 33.
 33. 39. 39. 39. 39. 33. 39. 33. 33. 39. 39. 33. 33. 25. 39. 39. 39. 39.
 39. 33. 33. 39. 25. 39. 39. 33. 33. 39. 33. 33. 33. 39. 39. 39. 39. 39.
 39. 39. 33. 33. 39. 25. 33. 33. 33. 33. 33. 39. 33. 39. 25. 33. 39. 39.
 39. 39. 39. 25. 33. 39. 33. 39. 33. 39. 39. 33. 39. 33. 33. 33. 39. 39.
 39. 33. 33. 33. 33. 33. 25. 39. 39. 25. 39. 39. 39. 39. 33. 33. 25. 39.
 39. 33. 33. 25. 33. 33. 39. 33. 39. 33. 39. 33. 39. 39. 33. 33. 33. 39.
 39. 33. 12. 33. 33. 39. 25. 39. 25. 33. 33. 33. 39. 39. 39. 39. 25. 33.
 39. 39. 39. 39. 33. 33. 33. 33. 33. 39. 39. 39. 33

[[1.930e+02 1.500e-01 2.580e+01 1.640e+00 5.000e+01]
 [2.145e+02 1.200e-01 2.460e+01 2.318e+01 4.990e+01]
 [2.296e+02 1.200e-01 2.790e+01 1.278e+01 5.000e+01]
 ...
 [2.020e+02 1.500e-01 2.520e+01 8.100e-01 4.990e+01]
 [1.980e+02 1.700e-01 3.250e+01 8.470e+00 4.990e+01]
 [1.963e+02 1.700e-01 3.160e+01 1.630e+00 5.000e+01]]


[29.  1. 18. ... 25. 11. 29.]


Akurasi: 0.12459016393442623


[12. 31. 12. 39. 39. 39. 35. 35. 31. 39. 39. 35. 39. 39. 31. 35. 12. 31.
 12. 12. 39. 39. 12. 39. 39. 39. 12. 12. 31. 39. 39. 39. 39. 12. 35. 39.
 35. 31. 39. 12. 12. 39. 35. 35. 39. 12. 39. 39. 39. 12. 25. 39. 39. 39.
 39. 12. 39. 35. 39. 39. 31. 12. 39. 39. 39. 35. 39. 39. 12. 25. 12. 39.
 39. 39. 31. 31. 39. 12. 31. 39. 39. 39. 39. 39. 39. 35. 39. 39. 39. 31.
 39. 39. 35. 39. 39. 39. 12. 12. 39. 35. 12. 12. 31. 31. 39. 12. 39. 39.
 31. 35. 39. 39. 12. 39. 35. 35. 12. 25. 39. 25. 12. 39. 39. 31. 39. 31.
 35. 35. 31. 39. 35. 35. 12. 35. 12. 12. 39. 39. 31. 12. 39. 39. 39. 12.
 39. 39. 39. 35. 39. 39. 39. 39. 39. 39. 35. 39. 12. 39. 25. 39. 35. 31.
 39. 39. 25. 39. 39. 39. 39.  0. 39. 35. 39. 31. 12. 39. 39. 39. 12. 39.
 35. 39. 31. 39. 35. 39. 39. 31. 39. 39. 31. 39. 39. 39. 31. 12. 39. 35.
 31. 35. 39. 39. 39. 31. 39. 39. 35. 39. 25. 39. 12. 39. 35. 31. 39. 39.
 35. 35. 12. 12. 39. 39. 12. 39. 39. 39. 35. 39. 39. 39. 35. 31.  0. 39.
 39. 25. 31. 35. 39. 35. 12. 31. 39. 35. 35. 39. 35